# This is a basic workflow to help you get started with Actions

name: Deploy on Web Files

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Install DotNet
        uses: actions/setup-dotnet@v2
      - run: dotnet build MyFirstWebApp
      
      - name: Verify the Public Folder
        run: ls -la public


     
